/*
 * Copies the web game into desktop/app/ and makes it work offline:
 * - Three.js r128 is bundled from the `three` npm package instead of cdnjs;
 * - Inter and Outfit are bundled from @fontsource instead of Google Fonts;
 * - a Content-Security-Policy that only allows the game's own files is added.
 * The web version itself is never modified.
 */
const fs = require('fs');
const path = require('path');

const desktopDir = path.resolve(__dirname, '..');
const gameDir = path.resolve(desktopDir, '..');
const outDir = path.join(desktopDir, 'app');
const nodeModules = path.join(desktopDir, 'node_modules');

function fail(message) {
  console.error(`prepare-app: ${message}`);
  process.exit(1);
}

function copyDir(from, to) {
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const src = path.join(from, entry.name);
    const dst = path.join(to, entry.name);
    if (entry.isDirectory()) copyDir(src, dst);
    else fs.copyFileSync(src, dst);
  }
}

// Fresh copy of the game files (never the desktop folder itself).
fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(outDir, { recursive: true });
for (const name of ['index.html', 'favicon.png']) fs.copyFileSync(path.join(gameDir, name), path.join(outDir, name));
for (const dir of ['css', 'js']) copyDir(path.join(gameDir, dir), path.join(outDir, dir));

// Three.js, pinned to the same release as the web version (r128 = 0.128.0).
const threeSrc = path.join(nodeModules, 'three', 'build', 'three.min.js');
if (!fs.existsSync(threeSrc)) fail('three.min.js not found. Run `npm install` first.');
const threeVersion = require(path.join(nodeModules, 'three', 'package.json')).version;
if (threeVersion !== '0.128.0') fail(`expected three@0.128.0 (r128), found ${threeVersion}`);
fs.mkdirSync(path.join(outDir, 'vendor', 'fonts'), { recursive: true });
fs.copyFileSync(threeSrc, path.join(outDir, 'vendor', 'three.min.js'));

// Fonts: the weights the CSS uses, Latin and Latin Extended only (English, French, names).
const FONTS = { inter: [400, 500, 600, 700], outfit: [500, 600, 700] };
let fontCss = '/* Generated by scripts/prepare-app.js from @fontsource packages. */\n';
let fontFiles = 0;
for (const [family, weights] of Object.entries(FONTS)) {
  const pkg = path.join(nodeModules, '@fontsource', family);
  if (!fs.existsSync(pkg)) fail(`@fontsource/${family} not found. Run \`npm install\` first.`);
  for (const weight of weights) {
    const css = fs.readFileSync(path.join(pkg, `${weight}.css`), 'utf8');
    for (const block of css.match(/@font-face\s*\{[^}]*\}/g) || []) {
      if (!/-latin-(ext-)?\d+-normal\.woff2/.test(block)) continue; // skip Cyrillic, Greek, Vietnamese…
      const file = block.match(/url\(\.\/files\/([^)]+\.woff2)\)/)[1];
      fs.copyFileSync(path.join(pkg, 'files', file), path.join(outDir, 'vendor', 'fonts', file));
      fontFiles += 1;
      // Keep only the woff2 source, pointing at the bundled copy.
      fontCss += `${block.replace(/src:[^;]+;/, `src: url(fonts/${file}) format('woff2');`)}\n`;
    }
  }
}
fs.writeFileSync(path.join(outDir, 'vendor', 'fonts.css'), fontCss);

// Point index.html at the bundled files and add a strict CSP.
const htmlPath = path.join(outDir, 'index.html');
let html = fs.readFileSync(htmlPath, 'utf8');
const replace = (pattern, replacement, what) => {
  if (!pattern.test(html)) fail(`could not find ${what} in index.html`);
  html = html.replace(pattern, replacement);
};
replace(/<script src="https:\/\/cdnjs\.cloudflare\.com\/ajax\/libs\/three\.js\/r128\/three\.min\.js"><\/script>/,
  '<script src="vendor/three.min.js"></script>', 'the Three.js CDN script');
replace(/<link rel="preconnect" href="https:\/\/fonts\.googleapis\.com" \/>\n<link rel="preconnect" href="https:\/\/fonts\.gstatic\.com" crossorigin \/>\n<link href="https:\/\/fonts\.googleapis\.com\/css2[^"]*" rel="stylesheet" \/>/,
  '<link rel="stylesheet" href="vendor/fonts.css" />', 'the Google Fonts links');
// style-src needs 'unsafe-inline' because the game sets a few inline styles
// (swatch colours, progress bars). No inline or remote scripts are allowed.
replace(/<meta charset="UTF-8" \/>/,
  '<meta charset="UTF-8" />\n<meta http-equiv="Content-Security-Policy" content="default-src \'self\'; script-src \'self\'; style-src \'self\' \'unsafe-inline\'; font-src \'self\'; img-src \'self\' data:; connect-src \'none\'; object-src \'none\'; base-uri \'none\'; form-action \'none\'" />',
  'the charset meta tag');
if (/https?:\/\//.test(html.replace(/<meta http-equiv[^>]+>/, ''))) {
  const leftover = html.match(/https?:\/\/[^"'\s]+/)[0];
  fail(`index.html still references a remote URL: ${leftover}`);
}
fs.writeFileSync(htmlPath, html);

console.log(`prepare-app: game copied to app/ with three.js ${threeVersion} and ${fontFiles} font files bundled (offline-ready).`);
